spring:
  application:
    name:payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/javadb
    username: root
    password: pramod
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:update
      show-sql:true
  properties:
    hibernate:
      format_sql:true
  database-platform: org.hibernate.dialect.MySQLDialect



  spring:
    kafka:
      bootstrap-servers: 15.206.166.88:9094

      consumer:
        group-id: payment-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.pramod.saga.commons.*"

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer






server:
  port: 8082



